version: '2'

services:
   db:
     image: 7cav/cavdb:stable
     container_name: db
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     ports:
         - "3306:3306"
     environment:
       MYSQL_ROOT_PASSWORD: xenforo
       MYSQL_DATABASE: 7cav_dev
       MYSQL_USER: xenforo
       MYSQL_PASSWORD: xenforo

   web:
     depends_on:
       - db
     image: 7cav/cavweb:stable
     container_name: web
     restart: always
     ports:
         - "80:80"
     environment:
       DB_HOST: db
       DB_USERNAME: xenforo
       DB_PASSWORD: xenforo
       DB_NAME: 7cav_dev
     volumes:
       - data:/var/www/html/data
       - internal_data:/var/www/html/internal_data
       - ./library/CavTools:/var/www/html/library/CavTools
       - ./js/CavTools:/var/www/html/js/CavTools
volumes:
    db_data:
    data:
    internal_data:
