version: '2'

services:
    db:
        image: 7cav/cavdb
        container_name: db
        restart: always
        environment:
            MYSQL_USER: xenforo
            MYSQL_PASSWORD: xenforo
            MYSQL_ROOT_PASSWORD: xenforo
            MYSQL_DATABASE: xenforo
        volumes:
            - db_data:/var/lib/mysql
        ports:
            - "3306:3306"

    web:
        depends_on:
        - db
        image: 7cav/cavweb
        restart: always
        environment:
            DB_HOST: db
            DB_USERNAME: xenforo
            DB_PASSWORD: xenforo
            DB_NAME: xenforo
        volumes:
            - data:/var/www/html/data
            - internal_data:/var/www/html/internal_data
            - ./js/CavTools:/var/www/html/js/CavTools
            - ./library/CavTools:/var/www/html/library/CavTools


    lb:
        image: dockercloud/haproxy:latest
        links:
            - web
        ports:
            - "8080:80"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock

volumes:
    db_data:
    data:
    internal_data:
    js:
    CavTools:
